name: Bug Report 🐛
description: Report a bug in Anzii framework
title: "[Bug]:"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report. We highly appreciate your effort. ❤️

  - type: checkboxes
    attributes:
      label: Latest version
      description: Did you test the latest version? It's possible your issue might have been fixed in the latest version.
      options:
        - label: I have tested the latest version
          required: true

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex.email@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: dropdown
    id: anzii
    attributes:
      label: Anzii package
      description: Which anzii package(s) are the source of the bug?
      options:
        - Core
        - Dman
        - Anzii-logger
        - "Don't know / other"
      multiple: true
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Anzii are you running?
      options:
        - 6.0.2 (latest)
        - 6.1.0

    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: What OS are you seeing the problem on?
      multiple: true
      options:
        - Ubuntu/Linux
        - Windows
        - Mac

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        **⚠️ Issues that we can't reproduce can't be fixed. Apologies**

      value: |

        Steps:
        1.
        2.

  - type: input
    id: reproduction
    attributes:
      label: Please provide a link to a minimal reproduction of the bug
  - type: textarea
    id: exception-or-error
    attributes:
      label: Please provide the exception or error you saw
      render: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct]
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
