name: Bug Report
description: Report a bug in Anzii framework
title: "[Bug]:"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
         Thanks for taking the time to fill out this bug report. We highly appreciate your effort.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which anzii package(s) are the source of the bug?
      options:
        - core
        - Don't know / other
      multiple: true
     validations:
        required: true


  
