name: Docs bug/feedback
description: Improve Anzii framework documentation.
labels: ["docs-bug"]
title: "[docs] "

body:
  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the issue in the title above ⬆️.

        Thanks for contributing by creating an issue. We highly appreciate all your effort! ❤️

  - type: input
    attributes:
      label: Search keywords
      description: Your issue may have already been reported! List the keywords you've used to search the [existing issues](https://github.com/iiprodakts/anzii/issues). This will also make your issue searchable for others.
      placeholder: e.g. text missing
    validations:
      required: true

  - type: input
    id: page-url
    attributes:
      label: Related page
      description: Which page of the documentation is this about?
      placeholder: https://anzii.com/
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Kind of issue
      description: What kind of problem are you facing?
      options:
        - Unclear explanations
        - Missing information
        - Broken demo
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Issue description
      description: |
        Let us know what went wrong when you were using this documentation and what we could do to improve it.
      value: |
        I was trying to understand ... and this ... happened

  - type: textarea
    attributes:
      label: Context
      description: What are you trying to accomplish? What brought you to this page? Your context can help us to come up with solutions that benefit the community as a whole.
