name: Check source code complise

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout" # Download code from the repository
        uses: actions/checkout@v4 # Public action
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: "Use NodeJS 18" # Setup node using version 14
        uses: actions/setup-node@v4 # Public action
        with:
          node-version: "18"

      - name: "Setup npm"
        run: |
          npm set @xcanchal:registry=https://npm.pkg.github.com/xcanchal
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: Install dependencies
        run: | # Install and link dependencies
          npm ci
          npx lerna bootstrap

      - name: Run tests # Run tests of all packages
        run: npm run test --workspaces
